<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FurinaPlayer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="WinRT\**" />
    <Compile Remove="WinRT.FurinaPlayerGenericHelpers\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Web.WebView2.Core.Projection">
      <HintPath>..\..\Microsoft.Web.WebView2.Core.Projection.dll</HintPath>
    </Reference>
    <Reference Include="WinRT.Runtime">
      <HintPath>..\..\WinRT.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.WinUI">
      <HintPath>..\..\Microsoft.WinUI.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\SonicWave.Core\SonicWave.Core.csproj" />
    <ProjectReference Include="..\SonicWave.Audio\SonicWave.Audio.csproj" />
    <ProjectReference Include="..\FurinaPlayer.UI\FurinaPlayer.UI.csproj" />
    <Reference Include="SkiaSharp.Views.Windows">
      <HintPath>..\..\SkiaSharp.Views.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.InteractiveExperiences.Projection">
      <HintPath>..\..\Microsoft.InteractiveExperiences.Projection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Windows.SDK.NET">
      <HintPath>..\..\Microsoft.Windows.SDK.NET.dll</HintPath>
    </Reference>
    <Reference Include="SkiaSharp">
      <HintPath>..\..\SkiaSharp.dll</HintPath>
    </Reference>
    <Reference Include="CommunityToolkit.Mvvm">
      <HintPath>..\..\CommunityToolkit.Mvvm.dll</HintPath>
    </Reference>
    <Reference Include="LibVLCSharp">
      <HintPath>..\..\LibVLCSharp.dll</HintPath>
    </Reference>
    <Reference Include="LiveChartsCore.SkiaSharpView.WinUI">
      <HintPath>..\..\LiveChartsCore.SkiaSharpView.WinUI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
