<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SonicWave.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="ATL">
      <HintPath>..\..\ATL.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <HintPath>..\..\Microsoft.EntityFrameworkCore.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>..\..\Microsoft.Data.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="MathNet.Numerics">
      <HintPath>..\..\MathNet.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>..\..\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
