<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SonicWave.Audio</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="NAudio.Core">
      <HintPath>..\..\NAudio.Core.dll</HintPath>
    </Reference>
    <Reference Include="NAudio">
      <HintPath>..\..\NAudio.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\SonicWave.Core\SonicWave.Core.csproj" />
    <Reference Include="NAudio.WinMM">
      <HintPath>..\..\NAudio.WinMM.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Wasapi">
      <HintPath>..\..\NAudio.Wasapi.dll</HintPath>
    </Reference>
    <Reference Include="LibVLCSharp">
      <HintPath>..\..\LibVLCSharp.dll</HintPath>
    </Reference>
    <Reference Include="WinRT.Runtime">
      <HintPath>..\..\WinRT.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Asio">
      <HintPath>..\..\NAudio.Asio.dll</HintPath>
    </Reference>
    <Reference Include="MathNet.Numerics">
      <HintPath>..\..\MathNet.Numerics.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
